spring.application.name=IBom

server.port=8081

#MariaDV 드라이버 설정
spring.datasource.driver-class-name=org.mariadb.jdbc.Driver

#DB 주소 설정 (포트번호 3307, DB db이름)
spring.datasource.url=jdbc:mariadb://localhost:3307/ibom

#계정 정보( roo, 비번 1234)
spring.datasource.username=root
spring.datasource.password=1234

#JPA 설정 (테이블 자동 생성 및 SQL 로그 출력)
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true